name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Installe Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installe dependancieces
        run: npm install

      - name: Deploy Firebase Hosting
        run: npm run build && npx firebase deploy --only hosting --token "${{ secrets.FIREBASE_ALASSANE_PORTFOLIO_TOKEN }}"
